// app/layout.js

import './globals.css'; // Import your global styles (if any)
import { Inter } from 'next/font/google';

// Optional: load a Google font (Inter in this case)
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
 